---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: index.md
  label: Homepage
- type: directory
  path: bungalows
  label: Rooms
  create: documents
  match: "*"
  templates:
  - room
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - facilities
  - room
  - activity
- type: directory
  path: _activities
  label: Activities
  create: all
  match: "**/*"
upload_dir: samurai
public_path: https://res.cloudinary.com/samuraibeach/samurai
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
