---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: index.md
  label: Homepage
- type: directory
  path: bungalows
  label: Rooms
  create: documents
  match: "**/*.md"
  templates:
  - room
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _activities
  label: Activities
  create: all
  match: "**/*"
upload_dir: samurai
public_path: https://res.cloudinary.com/samuraibeach/samurai
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
