---
label: Default
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: text
  name: permalink
  label: permalink
- type: text
  name: redirect_from
  label: redirect_from
- type: field_group_list
  name: covers
  label: covers
  fields:
  - type: text
    name: title
    label: title
  - type: text
    name: description
    label: description
  - type: file
    name: file
    label: Image
    description: Widescreen cropped image
    config:
      maxSize: '8'
  config:
    min: '1'
    max: '2'
    labelField: title
